### ISSUE TITLE
Need help for noise from arduino.

### ISSUE THREAD

**Issue by kraftZeug** [gratefulfrog/ArduGuitar#1]
Hey there.
I'm working on electric guitars with onboard midi controlers and i'm amazed at your work.
I wanted to get in touch with you for a practical question: how did you managed the noise from arduino ?

**Comment by gratefulfrog** [comment]
Hi KraftZeug,

I should first tell you that all my work has moved to gitlab, so please
look there for code etc.

I had noise on my first circuit, only. I believe that this was due to
several things:

   - lack of a proper PCB: This is in my opinion the main problem. At the
   time, I did not know much and used a proto-board for the components. This
   was a big source of noise. Later, I designed a proper PCB with ground plane
   and fill and the problem was mostly solved.
   - use of unshielded wires for digital data. Another source, but much
   less than the PCB. Use very short shielded wires, soldered !
   - over use of connectors for digital data. Solder your digital cables
   wherever possible.

With these problems fixed, my 2nd circuit and my future 3rd circuit are
noiseless.

Hope this helps!
Cheers,
Bob

**Comment by kraftZeug** [comment]
Thanks, you helped a lot.
My arduino is wired with dupont connectors and the data wires are not shielded, although guitar wires are. I'll check this..
About the code, I used tttapa's code, Control-Surface.
My next project will be an arduino based analog switching with Red Special (Brian May's guitar) like abilities.
If you're interested, you can find me on facebook and instagram..
Great work anyway, I'll follow to see your next project.

**Comment by gratefulfrog** [comment]
No problem, I'm happy to help.

I cannot stress enough the importance of making a proper PCB with proper
ground plane and ground fill. This is really the biggest source of noise.

Good luck with your project!
